// Generates supabase/seed.sql from src/lib/repo/seed.ts so demo and production
// catalogues never drift.   Run:  npx tsx scripts/generate-seed-sql.ts
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { seedAvailability, seedBarbers, seedPortfolio, seedServices, seedShop, SHOP_ID } from "../src/lib/repo/seed";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(", ")}]::text[]`;
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const j = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const s = seedShop;
const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts — edit src/lib/repo/seed.ts instead.",
  "-- Replace placeholder address/phone/socials with the real shop details.",
  "begin;",
  `insert into public.shops (id, name, tagline, address, city, phone, whatsapp, email, maps_query, lat, lng, socials, hours, timezone, settings) values (${[
    SHOP_ID, s.name, s.tagline, s.address, s.city, s.phone, s.whatsapp, s.email, s.mapsQuery, s.lat, s.lng,
  ].map(q).join(", ")}, ${j(s.socials)}, ${j(s.hours)}, ${q(s.timezone)}, ${j(s.settings)}) on conflict (id) do nothing;`,
  "",
];

for (const b of seedBarbers) {
  lines.push(
    `insert into public.barbers (id, shop_id, slug, name, title, bio, specialties, experience_years, rating, review_count, photo_url, phone, socials, active, sort_order) values (${[
      b.id, SHOP_ID, b.slug, b.name, b.title, b.bio, b.specialties, b.experienceYears, b.rating, b.reviewCount, b.photoUrl, b.phone, b.socials, b.active, b.sortOrder,
    ].map(q).join(", ")}) on conflict (id) do nothing;`,
  );
}
lines.push("");
for (const sv of seedServices) {
  lines.push(
    `insert into public.services (id, shop_id, slug, name, description, price, price_from, duration_minutes, category, icon, active, sort_order) values (${[
      sv.id, SHOP_ID, sv.slug, sv.name, sv.description, sv.price, sv.priceFrom, sv.durationMinutes, sv.category, sv.icon, sv.active, sv.sortOrder,
    ].map(q).join(", ")}) on conflict (id) do nothing;`,
  );
}
lines.push("");
for (const b of seedBarbers) {
  for (const sid of b.serviceIds) {
    lines.push(
      `insert into public.barber_services (barber_id, service_id, duration_override) values (${q(b.id)}, ${q(sid)}, ${q(b.durationOverrides[sid] ?? null)}) on conflict do nothing;`,
    );
  }
}
lines.push("");
for (const r of seedAvailability) {
  lines.push(
    `insert into public.availability (barber_id, weekday, start_time, end_time, breaks) values (${[r.barberId, r.weekday, r.start, r.end].map(q).join(", ")}, ${j(r.breaks)}) on conflict do nothing;`,
  );
}
lines.push("");
for (const p of seedPortfolio) {
  lines.push(
    `insert into public.portfolio_images (shop_id, barber_id, category, title, description, image_url, taken_on) values (${[SHOP_ID, p.barberId, p.category, p.title, p.description, p.imageUrl, p.date].map(q).join(", ")});`,
  );
}

lines.push(
  "",
  "-- ── Staff accounts ──────────────────────────────────────────────────────",
  "-- 1. Create the users in Supabase Dashboard → Authentication → Users (email + password).",
  "-- 2. Then grant their roles (replace the e-mails):",
  "-- update public.profiles set role = 'owner', can_view_revenue = true",
  "--   where id = (select id from auth.users where email = 'owner@barbertwiin.ma');",
  ...seedBarbers.map(
    (b) =>
      `-- update public.profiles set role = 'barber', barber_id = '${b.id}', full_name = '${b.name}'\n--   where id = (select id from auth.users where email = '${b.slug}@barbertwiin.ma');`,
  ),
  "-- update public.profiles set role = 'receptionist'",
  "--   where id = (select id from auth.users where email = 'accueil@barbertwiin.ma');",
  "commit;",
  "",
);

writeFileSync(join(__dirname, "..", "supabase", "seed.sql"), lines.join("\n"));
console.log("supabase/seed.sql written");
